# Generated by Django 3.1.5 on 2022-04-10 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0002_drawing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='time',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='title',
        ),
    ]
