# Generated by Django 3.1.5 on 2022-04-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0003_auto_20220410_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawing',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='drawing',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
