# Generated by Django 3.1.5 on 2022-04-10 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0004_auto_20220410_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
