# Generated by Django 3.1.5 on 2022-04-10 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0005_auto_20220410_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='time',
        ),
    ]
