# Generated by Django 3.1.5 on 2022-04-11 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0006_remove_drawing_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.DecimalField(decimal_places=3, max_digits=4)),
                ('y', models.DecimalField(decimal_places=3, max_digits=3)),
            ],
        ),
        migrations.AddField(
            model_name='drawing',
            name='drawing_points',
            field=models.ManyToManyField(to='coloring.Coord'),
        ),
    ]
