# Generated by Django 3.1.5 on 2022-04-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0008_auto_20220411_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coord',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coord',
            name='y',
            field=models.IntegerField(),
        ),
    ]
