# Generated by Django 3.1.5 on 2022-04-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0009_auto_20220411_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drawing',
            name='drawing_points',
        ),
        migrations.DeleteModel(
            name='Coord',
        ),
    ]
