# Generated by Django 3.1.5 on 2022-04-15 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coloring', '0012_auto_20220415_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='drawing',
            name='drawing_points',
            field=models.ManyToManyField(to='coloring.Coord'),
        ),
    ]
